package com.bitwiseglobal.npd_space.topic1.project_two;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimpleDataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SimpleDataObject() {
    }




}